<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>hcl</string>
   </array>
  <key>name</key>
  <string>hcl</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.hcl</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(wordsig|boolsig|quote)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.hcl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#sig</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.hcl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(word|bool)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.hcl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#circ</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hcl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>circ</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#none</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(in)</string>
          <key>name</key>
          <string>keyword.hcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
          <key>name</key>
          <string>variable.hcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(=)</string>
          <key>name</key>
          <string>punctuation.hcl</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#value</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>((#.*)|(//.*))</string>
          <key>name</key>
          <string>comment.hcl</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.hcl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.hcl</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.hcl</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>none</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s+)</string>
          <key>name</key>
          <string>text.hcl</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(0x[0-9a-fA-F]+)</string>
          <key>name</key>
          <string>constant.numeric.hcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(0b[01]+)</string>
          <key>name</key>
          <string>constant.numeric.hcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.hcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+|\*|-|/|(&amp;)|(\|)|(\^)|(!)|(~))</string>
          <key>name</key>
          <string>punctuation.hcl</string>
        </dict>
       </array>
    </dict>
    <key>quote</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.hcl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#quote__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.hcl</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>quote__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\x{0027}]*)</string>
          <key>name</key>
          <string>string.hcl</string>
        </dict>
       </array>
    </dict>
    <key>sig</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
          <key>name</key>
          <string>entity.name.class.hcl</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#quote</string>
        </dict>
       </array>
    </dict>
    <key>value</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#none</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(:|&amp;&amp;|\|\||==)</string>
          <key>name</key>
          <string>punctuation.hcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(in)</string>
          <key>name</key>
          <string>keyword.hcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
          <key>name</key>
          <string>variable.hcl</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hcl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#value__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hcl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hcl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#value__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hcl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>value__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
          <key>name</key>
          <string>entity.name.class.hcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.hcl</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>value__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#none</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>([a-zA-Z][0-9a-zA-Z]*(?:_[0-9a-zA-Z]+)*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.hcl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#value__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hcl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\d+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.hcl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#value__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hcl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#value</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>value__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#value</string>
        </dict>
       </array>
    </dict>
    <key>value__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#value</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
